dependencies:
  cupertino_icons: ^1.0.6
  flet: 0.24.1
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  serious_python: 0.8.0
  url_strategy: ^0.2.0
dependency_overrides:
  wakelock_plus: ^1.2.5
  web: ^1.0.0
description: null
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.6
environment:
  sdk: '>=3.1.5 <4.0.0'
flutter:
  assets:
  - app/app.zip
  - app/app.zip.hash
  uses-material-design: true
flutter_launcher_icons:
  android: true
  image_path: images/icon.png
  image_path_android: images/icon.png
  image_path_ios: images/icon.png
  ios: true
  macos:
    generate: true
    image_path: images/icon.png
  remove_alpha_ios: true
  web:
    generate: true
    image_path: images/icon.png
  windows:
    generate: true
    icon_size: 256
    image_path: images/icon.png
flutter_native_splash:
  android: true
  android_12:
    color: '#ffffff'
    color_dark: '#333333'
    image: images/icon.png
    image_dark: images/icon.png
  color: '#ffffff'
  color_dark: '#222222'
  image: images/icon.png
  image_android: images/icon.png
  image_dark: images/icon.png
  image_dark_android: images/icon.png
  image_dark_ios: images/icon.png
  image_dark_web: images/icon.png
  image_ios: images/icon.png
  image_web: images/icon.png
  ios: true
  web: true
name: authtest
publish_to: none
version: 1.0.0+1
